features:
  - name: EMOTIONAL_INTENSITY
    graph_mode: BAR
  - name: MOOD
    graph_mode: COLOR
  - name: DESCRIPTIVE_DETAIL_LEVEL
    graph_mode: SAVE_ONLY
  - name: MYSTERY_LEVEL
    graph_mode: SAVE_ONLY
  - name: PACING
    graph_mode: SAVE_ONLY
  - name: LEVEL_OF_SUSPENSE
    graph_mode: SAVE_ONLY
  - name: "Smell Sensory Detail Level"
    graph_mode: SAVE_ONLY
    customizations:
      levels:
        - "none"
        - "low"
        - "medium"
        - "high"
      color_map:
        "0": "#FFFFFF"
        "1": "#CC99CC"
        "2": "#CC99CC"
        "3": "#800080"
