features:
  - name: EMOTIONAL_INTENSITY
    result_collection_mode: NUMBER_REPRESENTATION
  - name: MOOD
    result_collection_mode: FIELD_NAME
  - name: DESCRIPTIVE_DETAIL_LEVEL
    result_collection_mode: NUMBER_REPRESENTATION
  - name: MYSTERY_LEVEL
    result_collection_mode: NUMBER_REPRESENTATION
  - name: PACING
    result_collection_mode: NUMBER_REPRESENTATION
  - name: LEVEL_OF_SUSPENSE
    result_collection_mode: NUMBER_REPRESENTATION
  - name: "Smell Sensory Detail Level"
    result_collection_mode: NUMBER_REPRESENTATION
    customizations:
      levels:
        - "none"
        - "low"
        - "medium"
        - "high"
      color_map:
        "0": "#FFFFFF"
        "1": "#CC99CC"
        "2": "#CC99CC"
        "3": "#800080"
